### ISSUE TITLE
Season Progress edit.

### ISSUE THREAD

**Issue by mastervash** [WayneYellow/Deep-Rock-Galactic-Save-Editor#1]
Good day, first just a big thank you for this updated tool. I lost several 100 lvls after reinstalling windows even though I thought I had backups of my save, turns out the save it grabbed was over a year old. In any case I'm mostly back to where I was now, except I can't get the Seasonal to show as completed. 

I'm entering Rank 100 Progress 4999 and Scrip to 100, as I had already finished it, but it's still showing that I'm at level 1 when I boot into the game. Am I entering something incorrectly or has there been an update since the tool was last released and it stopped working for the Season XP. 

In either case, big thank you, I was actually considering no longer Rocking and Stoning before finding the tool, so massive gratitude from me.

**Comment by WayneYellow** [comment]
Thank you for using my tool. Based on your issue, I can provide the following solutions. Please follow the steps below to troubleshoot the error:
First, I assume that you are using the first installation method. Please confirm that the version you download is the latest version (v1.0.2). The version number should be displayed in the name of the downloaded .zip file as well as the executable (.exe) file. The issue with modifying the level does exist in versions before 1.0.1, but it has been fixed in version 1.0.2.
Second, if your current season progress is completely 0, it may cause the editor to be unable to modify its level. I suggest you play a game to earn some seasonal experience before using the editor to modify your seasonal level.  If you encounter this problem, I'm sorry that it was not stated in the documentation before. This is a known problem and I may fix it in a future version.
Third, make sure you open the correct game save. You can view and switch the currently used save in the options>>save menu in the game (it is also recommended to make regular backups from this interface). Ensure that the save file you have open in the editor is your most recent one (or the one you intend to play), and remember to click the "save" button in the bottom right corner of the editor after making your edits. The program will prompt you when the save is successful. Only then should you close the editor and verify in-game that you have the edited save open.
If the above solutions does not resolve your issue, please reply to this message and I will deal with it asap.

**Comment by mastervash** [comment]
can confirm that I used the first installation method with version 1.0.2.

You were correct, completing the first level of the season manually before editing the save did the trick. I was able to set the level to 99 with 4999 progress. 

Thank you again for your help and for the tool!
